### ISSUE TITLE
Update GitOps Hands-On Welcome page for ongoing campaign

### ISSUE THREAD

**Issue by mewzherder** [weaveworks/eks-appmesh-profile#19]
Could we change back some of the elements of the welcome page?
I made edits in this google doc: https://docs.google.com/document/d/1qvS0mssHjzICPSHH3TCyu6AUbxPFrRDzRHpPn156FcQ/edit#heading=h.6uidh43o18i4

LMK. Thanks!

**Comment by stefanprodan** [comment]
Fixed by https://github.com/weaveworks/eks-appmesh-profile/commit/60757f84e3b6867c0861af7bd2190915a302ec41
